services:
  app:
    build:
      context: ./php
      dockerfile: Dockerfile
    container_name: php
    volumes:
      - ./php/src:/var/www/html/example
      - /src/node_modules
  web:
    image: nginx:1.25.1-alpine-slim
    container_name: nginx
    ports:
      - 8080:80
    volumes:
      - ./php/src:/var/www/html/example
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
  db:
    image: mysql:8.0.34
    container_name: mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: root
      TZ: Asia/Tokyo
    volumes:
      - ./data:/var/lib/mysql
      - ./my.cnf:/etc/mysql/conf.d/my.cnf
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql
      - PMA_USER=root
      - PMA_PASSWORD=root
    ports:
      - 4040:80

